routes/admin.php
<?php

use App\Http\Controllers\Admin\CompanyController;
use App\Http\Controllers\Admin\EmployeeController;
use App\Http\Controllers\Admin\Ajax\CompanyController as AjaxCompanyController;
use Illuminate\Support\Facades\Route;

Route::resource('company', CompanyController::class);

Route::get('/company/{company}/generate-pdf', [CompanyController::class, 'generatePDF'])
  ->name('company.generate_pdf');

Route::get('/company/{company}/import_excel/create', [CompanyController::class, 'createImportExcel'])
  ->name('company.import_excel.create');

Route::post('/company/{company}/import_excel', [CompanyController::class, 'storeImportExcel'])
  ->name('company.import_excel.store');

Route::get('/ajax-get-company', [AjaxCompanyController::class, 'index'])
  ->middleware('ajax')
  ->name('ajax.company.index');
  
Route::resource('employee', EmployeeController::class);

routes/web.php
<?php

use App\Models\Role;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])
    ->middleware(['web', 'auth', 'authorize:' . Role::ADMIN, 'verified'])
    ->name('home');

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'website',
    ];

    public function employees()
    {
        return $this->hasMany(Employee::class, 'company_id');
    }

    public function logo()
    {
        return $this->morphOne(FileStorage::class, 'file');
    }
}

app/Http/Controllers/Admin/Ajax/CompanyController.php
<?php

namespace App\Http\Controllers\Admin\Ajax;

use App\Http\Controllers\Controller;
use App\Models\Company;
use Illuminate\Http\Request;

class CompanyController extends Controller
{
    public function index(Request $request)
    {
        $companies = Company::select('id', 'name as text')
            ->where('name', 'LIKE',  '%' . trim($request->term) . '%')
            ->orderBy('name', 'asc')->simplePaginate(5);
            
        return response()->json([
            "results" => $companies->items(),
            "pagination" => [
                "more" => !!$companies->nextPageUrl()
            ]
        ]);
    }

    public function store(Request $request)
    {
        //
    }

    public function show($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Admin/CompanyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Extensions\ResponseExtension;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\CompanyRequest;
use App\Http\Requests\ImportRequest;
use App\Models\Company;
use App\Services\Admin\CompanyService;
use Exception;
use Throwable;

class CompanyController extends Controller
{
    private $response;

    public function __construct(ResponseExtension $responseExtension)
    {
        $this->response = $responseExtension;
    }

    public function index()
    {
        $companies = Company::with('logo')->simplePaginate(5);
        return response()->json($companies); 
    }

    public function create()
    {
        return response()->json($company);
    }

    public function store(CompanyRequest $request, CompanyService $companyService)
    {
        $companyService->store($request);

        return $this->response->success('Storing company success.');
    }

    public function show(Company $company)
    {
        $company->load(['logo', 'employees']);
        return response()->json($company);
        // return view('admin.company.show', compact('company'));
    }

    public function edit(Company $company)
    {
        return view('admin.company.edit', compact('company'));
    }

    public function update(CompanyRequest $request, Company $company, CompanyService $companyService)
    {
        $companyService->update($request, $company);

        return $this->response->success('Updating company success.');
    }

    public function destroy(Company $company, CompanyService $companyService)
    {
        $companyService->destroy($company);

        return $this->response
            ->to('admin.company.index')
            ->success('Deleting company success.');
    }

    public function generatePDF(Company $company)
    {
        $company->load('employees');

        $pdf = \PDF::loadView('pdf.company', compact('company'));

        return $pdf->download('company-employees.pdf');
    }

    public function createImportExcel(Company $company)
    {
        return view('admin.company.import_excel', compact('company'));
    }

    public function storeImportExcel(ImportRequest $request, Company $company, CompanyService $companyService)
    {
        $import = $companyService->importExcel($request, $company);

        if($import !== true) {
            return $import;
        }

        return $this->response->success('Importing employees success.');
    }
}

resources/views/admin/company/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
          <span>Create company</span>
          <a class="btn btn-sm btn-secondary" href="{{ route('admin.company.index') }}" role="button">Back</a>
        </div>

        <div class="card-body">
          @if($errors->any())
          <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">Whoops, something went wrong.</h4>
            <ul>
              @foreach($errors->all() as $error)
              <li>{{ $error }}</li>
              @endforeach
            </ul>
          </div>
          @endif

          <form method="POST" action="{{ route('admin.company.store') }}" enctype="multipart/form-data">
            @csrf

            <div class="form-group mb-3">
              <label>Logo</label>
              <div class="custom-file">
                <input type="file" class="custom-file-input" id="exampleInputFile" name="logo">
                <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                <script>
                  const inputFile = document.getElementById('exampleInputFile')
                  const inputFileLabel = document.querySelector('label[for=exampleInputFile]')

                  inputFile.addEventListener('change', (e) => {
                    inputFileLabel.innerHTML = e.target.files[0].name
                  })
                </script>
              </div>
            </div>

            <div class="form-group">
              <label for="exampleInputName">Name</label>
              <input type="text" class="form-control" id="exampleInputName" aria-describedby="nameHelp" name="name" value="{{ old('name') }}">
              <!-- <small id="nameHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
            </div>
            <div class="form-group">
              <label for="exampleInputEmail">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" name="email" value="{{ old('email') }}">
              <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
            </div>
            <div class="form-group">
              <label for="exampleInputWebsite">Website</label>
              <input type="text" class="form-control" id="exampleInputWebsite" aria-describedby="websiteHelp" name="website" value="{{ old('website') }}">
              <!-- <small id="websiteHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
            </div>
            <button type="submit" class="btn btn-primary">Store</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/company/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
          <span>Edit company</span>
          <div>
            <a class="btn btn-sm btn-secondary" href="{{ route('admin.company.show', ['company' => $company->id]) }}" role="button">Back</a>
          </div>
        </div>

        <div class="card-body">
          @if($errors->any())
          <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">Whoops, something went wrong.</h4>
            <ul>
              @foreach($errors->all() as $error)
              <li>{{ $error }}</li>
              @endforeach
            </ul>
          </div>
          @endif

          <form method="POST" action="{{ route('admin.company.update', ['company' => $company->id]) }}" enctype="multipart/form-data">
            @csrf
            @method('put')

            <div class="form-group mb-3">
              <label>Logo</label>
              <div class="custom-file">
                <input type="file" class="custom-file-input" id="exampleInputFile" name="logo">
                <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                <script>
                  const inputFile = document.getElementById('exampleInputFile')
                  const inputFileLabel = document.querySelector('label[for=exampleInputFile]')

                  inputFile.addEventListener('change', (e) => {
                    inputFileLabel.innerHTML = e.target.files[0].name
                  })
                </script>
              </div>
              <small id="logoHelp" class="form-text text-muted">if you don't want to change the old logo, ignore this field.</small>
            </div>

            <div class="form-group">
              <label for="exampleInputName">Name</label>
              <input type="text" class="form-control" id="exampleInputName" aria-describedby="nameHelp" name="name" value="{{ old('name') ?? $company->name }}">
              <!-- <small id="nameHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
            </div>
            <div class="form-group">
              <label for="exampleInputEmail">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" name="email" value="{{ old('email') ?? $company->email }}">
              <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
            </div>
            <div class="form-group">
              <label for="exampleInputWebsite">Website</label>
              <input type="text" class="form-control" id="exampleInputWebsite" aria-describedby="websiteHelp" name="website" value="{{ old('website') ?? $company->website }}">
              <!-- <small id="websiteHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/company/import_excel.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
          <span>Import employee</span>
          <a class="btn btn-sm btn-secondary" href="{{ route('admin.company.show', ['company' => $company->id]) }}" role="button">Back</a>
        </div>

        <div class="card-body">
          @if($errors->any())
          <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">Whoops, something went wrong.</h4>
            <ul>
              @foreach($errors->all() as $error)
              <li>{{ $error }}</li>
              @endforeach
            </ul>
          </div>
          @endif

          <form method="POST" action="{{ route('admin.company.import_excel.store', ['company' => $company->id]) }}" enctype="multipart/form-data">
            @csrf

            <div class="form-group mb-3">
              <label>Excel</label>
              <div class="custom-file">
                <input type="file" class="custom-file-input" id="exampleInputFile" name="file">
                <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                <script>
                  const inputFile = document.getElementById('exampleInputFile')
                  const inputFileLabel = document.querySelector('label[for=exampleInputFile]')

                  inputFile.addEventListener('change', (e) => {
                    inputFileLabel.innerHTML = e.target.files[0].name
                  })
                </script>
              </div>
            </div>
            <button type="submit" class="btn btn-primary">Store</button>
          </form>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-4">
      <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
          <span>Download template excel</span>
        </div>

        <div class="card-body d-flex justify-content-center align-items-center">
          <a class="btn btn-primary" href="{{ asset('template/import-employees-template.xlsx') }}" role="button">Download</a>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/company/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
          <span>Company</span>
          <a class="btn btn-sm btn-primary" href="{{ route('admin.company.create') }}" role="button">Create</a>
        </div>

        <div class="card-body">
          @if($companies->count() > 0)
          <table class="table table-hover">
            <thead>
              <tr>
                <th class="col-1">ID</th>
                <th class="col-5">Name</th>
                <th class="col-3">Email</th>
                <th class="col-3 text-center">Action</th>
              </tr>
            </thead>
            <tbody>
              @foreach($companies as $company)
              <tr>
                <th scope="row">{{ $company->id }}</th>
                <td>{{ $company->name }}</td>
                <td>{{ $company->email }}</td>
                <td class="text-center">
                  <a class="btn btn-sm btn-primary mb-1 mb-md-0" href="{{ route('admin.company.show', ['company' => $company->id]) }}" role="button">Detail</a>
                  <button type="button" class="btn btn-sm btn-danger" onclick="event.preventDefault();document.getElementById('delete-company-{{ $company->id }}').submit();">Delete</button>

                  <form id="delete-company-{{ $company->id }}" action="{{ route('admin.company.destroy', ['company' => $company->id]) }}" method="POST" class="d-none">
                    @csrf
                    @method('delete')
                  </form>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>

          <div class="d-flex justify-content-end">
            {{ $companies->links() }}
          </div>
          @else
          <span class="d-block text-center text-muted">Companies is empty</span>
          @endif
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin/company/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
          <span>Detail company</span>
          <div>
            <a class="btn btn-sm btn-secondary mb-1 mb-md-0" href="{{ route('admin.company.index') }}" role="button">Back</a>
            <a class="btn btn-sm btn-primary mb-1 mb-md-0" href="{{ route('admin.company.import_excel.create', ['company' => $company->id]) }}" role="button">Import excel</a>
            <a class="btn btn-sm btn-primary mb-1 mb-md-0" href="{{ route('admin.company.generate_pdf', ['company' => $company->id]) }}" role="button">Generate pdf</a>
            <a class="btn btn-sm btn-success mb-1 mb-md-0" href="{{ route('admin.company.edit', ['company' => $company->id]) }}" role="button">Edit</a>
            <button type="button" class="btn btn-sm btn-danger mb-1 mb-md-0" onclick="event.preventDefault();document.getElementById('delete-company-{{ $company->id }}').submit();">Delete</button>

            <form id="delete-company-{{ $company->id }}" action="{{ route('admin.company.destroy', ['company' => $company->id]) }}" method="POST" class="d-none">
              @csrf
              @method('delete')
            </form>
          </div>
        </div>

        <div class="card-body row">
          <div class="col-12 col-md-6 col-lg-4">
            <div class="card">
              <div class="card-body">
                <span>Logo</span>
                <div class="pt-1" style="max-height: 17rem;">
                  <img class="img-fluid" src="{{ $company->logo->url }}" alt="{{ $company->logo->name }}">
                </div>
              </div>
            </div>
          </div>
          <div class="col-12 col-md-6 col-lg-8 pt-3 pt-md-0">
            <div class="form-group">
              <label for="exampleInputName">Name</label>
              <input type="text" class="form-control disabled" id="exampleInputName" aria-describedby="nameHelp" name="name" value="{{ $company->name }}" disabled>
            </div>
            <div class="form-group">
              <label for="exampleInputEmail">Email address</label>
              <input type="email" class="form-control disabled" id="exampleInputEmail" aria-describedby="emailHelp" name="email" value="{{ $company->email }}" disabled>
              <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
            </div>
            <div class="form-group">
              <label for="exampleInputWebsite">Website</label>
              <input type="text" class="form-control disabled" id="exampleInputWebsite" aria-describedby="websiteHelp" name="website" value="{{ $company->website }}" disabled>
              <!-- <small id="websiteHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
            </div>
            <div class="form-group">
              <label for="exampleInputEmployees">Employees</label>
              <input type="text" class="form-control disabled" id="exampleInputEmployees" aria-describedby="employeesHelp" name="employees" value="{{ $company->employees->count() }}" disabled>
              <!-- <small id="employeesHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection