routes/admin.php
<?php

use App\Http\Controllers\Admin\CompanyController;
use App\Http\Controllers\Admin\EmployeeController;
use App\Http\Controllers\Admin\Ajax\CompanyController as AjaxCompanyController;
use Illuminate\Support\Facades\Route;

Route::resource('company', CompanyController::class);

Route::get('/company/{company}/generate-pdf', [CompanyController::class, 'generatePDF'])
  ->name('company.generate_pdf');

Route::get('/company/{company}/import_excel/create', [CompanyController::class, 'createImportExcel'])
  ->name('company.import_excel.create');

Route::post('/company/{company}/import_excel', [CompanyController::class, 'storeImportExcel'])
  ->name('company.import_excel.store');

Route::get('/ajax-get-company', [AjaxCompanyController::class, 'index'])
  ->middleware('ajax')
  ->name('ajax.company.index');
  
Route::resource('employee', EmployeeController::class);

routes/web.php
<?php

use App\Models\Role;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])
    ->middleware(['web', 'auth', 'authorize:' . Role::ADMIN, 'verified'])
    ->name('home');

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
    ];

    public function company()
    {
        return $this->belongsTo(Company::class, 'company_id');
    }
}

app/Http/Controllers/Admin/EmployeeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Extensions\ResponseExtension;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\EmployeeRequest;
use App\Models\Employee;
use App\Services\Admin\EmployeeService;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    private $response;

    public function __construct(ResponseExtension $responseExtension)
    {
        $this->response = $responseExtension;
    }

    public function index()
    {
        $employees = Employee::with('company')->simplePaginate(5);

        return view('admin.employee.index', compact('employees'));
    }

    public function create()
    {
        return view('admin.employee.create');
    }

    public function store(EmployeeRequest $request, EmployeeService $employeeService)
    {
        $employeeService->store($request);

        return $this->response->success('Storing employee success.');
    }

    public function show(Employee $employee)
    {
        $employee->load('company');

        return view('admin.employee.show', compact('employee'));
    }

    public function edit(Employee $employee)
    {
        $employee->load('company');

        return view('admin.employee.edit', compact('employee'));
    }

    public function update(EmployeeRequest $request, Employee $employee, EmployeeService $employeeService)
    {
        $employeeService->update($request, $employee);

        return $this->response->success('Updating employee success.');
    }

    public function destroy(Employee $employee, EmployeeService $employeeService)
    {
        $employeeService->destroy($employee);

        return $this->response
            ->to('admin.employee.index')
            ->success('Deleting employee success.');
    }
}

resources/views/admin/employee/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
          <span>Create employee</span>
          <a class="btn btn-sm btn-secondary" href="{{ route('admin.employee.index') }}" role="button">Back</a>
        </div>

        <div class="card-body">
          @if($errors->any())
          <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">Whoops, something went wrong.</h4>
            <ul>
              @foreach($errors->all() as $error)
              <li>{{ $error }}</li>
              @endforeach
            </ul>
          </div>
          @endif

          <form method="POST" action="{{ route('admin.employee.store') }}">
            @csrf

            <div class="form-group">
              <label for="exampleInputCompany">Name</label>
              <select id="exampleInputCompany" class="js-example-basic-single w-100" name="company_id">

              </select>
              <!-- <small id="nameHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
            </div>

            <div class="form-group">
              <label for="exampleInputName">Name</label>
              <input type="text" class="form-control" id="exampleInputName" aria-describedby="nameHelp" name="name" value="{{ old('name') }}">
              <!-- <small id="nameHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
            </div>
            <div class="form-group">
              <label for="exampleInputEmail">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" name="email" value="{{ old('email') }}">
              <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
            </div>
            <button type="submit" class="btn btn-primary">Store</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@section('script')
<script>
  $('#exampleInputCompany').select2({
    theme: 'bootstrap4',
    placeholder: "Select a company",
    width: '100%',
    ajax: {
      url: "{{ route('admin.ajax.company.index') }}",
      dataType: 'json',
      delay: 250,
      data: function(params) {
        return {
          term: params.term || '',
          page: params.page || 1
        }
      },
      cache: true
    }
  });
</script>
@endsection

resources/views/admin/employee/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
          <span>Edit employee</span>
          <div>
            <a class="btn btn-sm btn-secondary" href="{{ route('admin.employee.show', ['employee' => $employee->id]) }}" role="button">Back</a>
          </div>
        </div>

        <div class="card-body">
          @if($errors->any())
          <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">Whoops, something went wrong.</h4>
            <ul>
              @foreach($errors->all() as $error)
              <li>{{ $error }}</li>
              @endforeach
            </ul>
          </div>
          @endif

          <form method="POST" action="{{ route('admin.employee.update', ['employee' => $employee->id]) }}">
            @csrf
            @method('put')

            <div class="form-group">
              <label for="exampleInputCompany">Name</label>
              <select id="exampleInputCompany" class="js-example-basic-single w-100" name="company_id"></select>
              <!-- <small id="nameHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
            </div>

            <div class="form-group">
              <label for="exampleInputName">Name</label>
              <input type="text" class="form-control" id="exampleInputName" aria-describedby="nameHelp" name="name" value="{{ old('name') ?? $employee->name }}">
              <!-- <small id="nameHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
            </div>
            <div class="form-group">
              <label for="exampleInputEmail">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" name="email" value="{{ old('email') ?? $employee->email }}">
              <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@section('script')
<script>
  $('#exampleInputCompany').select2({
    theme: 'bootstrap4',
    placeholder: "Select a company",
    width: '100%',
    data: [{
      id: new Number('{{ $employee->company->id }}'),
      text: "{{ $employee->company->name }}"
    }],
    ajax: {
      url: "{{ route('admin.ajax.company.index') }}",
      dataType: 'json',
      delay: 250,
      data: function(params) {
        return {
          term: params.term || '',
          page: params.page || 1
        }
      },
      cache: true
    }
  });
</script>
@endsection

resources/views/admin/employee/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <span>Employee</span>
                    <a class="btn btn-sm btn-primary" href="{{ route('admin.employee.create') }}" role="button">Create</a>
                </div>

                <div class="card-body">
                    @if($employees->count() > 0)
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th class="col-1">ID</th>
                                <th class="col-5">Name</th>
                                <th class="col-3">Company</th>
                                <th class="col-3 text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($employees as $employee)
                            <tr>
                                <th scope="row">{{ $employee->id }}</th>
                                <td>{{ $employee->name }}</td>
                                <td>{{ $employee->company->name }}</td>
                                <td class="text-center">
                                    <a class="btn btn-sm btn-primary mb-1 mb-md-0" href="{{ route('admin.employee.show', ['employee' => $employee->id]) }}" role="button">Detail</a>
                                    <button type="button" class="btn btn-sm btn-danger" onclick="event.preventDefault();document.getElementById('delete-employee-{{ $employee->id }}').submit();">Delete</button>

                                    <form id="delete-employee-{{ $employee->id }}" action="{{ route('admin.employee.destroy', ['employee' => $employee->id]) }}" method="POST" class="d-none">
                                        @csrf
                                        @method('delete')
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>

                    <div class="d-flex justify-content-end">
                        {{ $employees->links() }}
                    </div>
                    @else
                    <span class="d-block text-center text-muted">Employee is empty</span>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/employee/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
          <span>Detail employee</span>
          <div>
            <a class="btn btn-sm btn-secondary" href="{{ route('admin.employee.index') }}" role="button">Back</a>
            <a class="btn btn-sm btn-success mb-1 mb-md-0" href="{{ route('admin.employee.edit', ['employee' => $employee->id]) }}" role="button">Edit</a>
            <button type="button" class="btn btn-sm btn-danger" onclick="event.preventDefault();document.getElementById('delete-employee-{{ $employee->id }}').submit();">Delete</button>

            <form id="delete-employee-{{ $employee->id }}" action="{{ route('admin.employee.destroy', ['employee' => $employee->id]) }}" method="POST" class="d-none">
              @csrf
              @method('delete')
            </form>
          </div>
        </div>

        <div class="card-body">
          <div class="form-group">
            <label for="exampleInputName">Name</label>
            <input type="text" class="form-control disabled" id="exampleInputName" aria-describedby="nameHelp" name="name" value="{{ $employee->name }}" disabled>
          </div>
          <div class="form-group">
            <label for="exampleInputEmail">Email address</label>
            <input type="email" class="form-control disabled" id="exampleInputEmail" aria-describedby="emailHelp" name="email" value="{{ $employee->email }}" disabled>
            <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
          </div>
          <div class="form-group">
            <label for="exampleInputCompany">Company</label>
            <input type="text" class="form-control disabled" id="exampleInputCompany" aria-describedby="companyHelp" name="company" value="{{ $employee->company->name }}" disabled>
            <!-- <small id="companyHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection